service: money-minder-api

useDotenv: true


provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  architecture: x86_64
  # apiGateway:
  #   apiKeys:
  #     - money-minder-primary-key
  # environment:
  #   BUCKET: !GetAtt S3Bucket.Arn
  #   SECRET_EGG: ${ssm:/SECRET_EGG}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: !GetAtt Transaction.Arn
  
plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-ignore
  - serverless-python-requirements
  - serverless-offline
package:
  individually: true
  patterns:
    - "!*/**"
    - "!**"
  exclude:
    - .env/**

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true
  pythonRequirements:
    dockerizePip: false
    # dockerImage: public.ecr.aws/sam/build-python3.8:latest-arm64
    # dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]
    # slim: true
    layer:
      name: FastAPI-Lambda-Function
      description: FastAPI-Lambda-Function API Layer
      compatibleRuntimes:
        - python3.8
    # useDownloadCache: true
    # useStaticCache: true


resources:
  Resources:
    Transaction:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:table_transaction_name}
        AttributeDefinitions:
          - AttributeName: Title
            AttributeType: S
          - AttributeName: Uid
            AttributeType: S
        KeySchema:
          - AttributeName: Title
            KeyType: HASH
          - AttributeName: Uid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


functions:
  # app:
  #   handler: lambdas/getUsers/handler.handler
  #   runtime: python3.8
  #   environment:
  #     STAGE: ${self:provider.stage}
  #   layers:
  #     - { Ref: PythonRequirementsLambdaLayer }
  #   package:
  #     patterns:
  #       - "lambdas/getUsers/**"
  #   events:
  #     - http:
  #         method: any
  #         path: /{proxy+}
  #         cors: true
  app:
    handler: lambdas/transaction/handler-transaction.handler
    runtime: python3.8
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    package:
      patterns:
        - "lambdas/transaction/**"
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
  


